name: Deploy IAC Terraform

on: 
    push: 
        branches: 
            - infra

jobs:
    terraform:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with: 
                terraform_version: 1.4.0
            
            - name: Initializa Terraform Backend
              uses: hashicorp/setup-terraform@v1
              with:
                backend-config: |
                     bucket = "mybucket-terraform-tfstate"
                     key    = "terraform.tfstate"
                     region = "us-east-1"
              env: 
                AWS_ACCESS_KEY_ID: ${{  secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name:  Terraform Init
              run: terraform init
            
            - name: Apply Terraform changes
              run: terraform apply -auto-approve